name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate Snake Animation (Light Mode)
        run: |
          curl -o dist/github-contribution-grid-snake.svg https://github.com/Platane/snk/raw/output/github-contribution-grid-snake.svg

      - name: Generate Snake Animation (Dark Mode)
        run: |
          curl -o dist/github-contribution-grid-snake-dark.svg https://github.com/Platane/snk/raw/output/github-contribution-grid-snake-dark.svg
